export default {
  SERVER_ERROR: "SERVER_ERROR",

  GET_USERS_SUCCESS: "GET_USERS_SUCCESS",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  FORGOT_PASSWORD_SUCCESS: "FORGOT_PASSWORD_SUCCESS",
  GET_CURRENT_USER_SUCCESS: "GET_CURRENT_USER_SUCCESS",
  UPDATE_STATUS_CAPTION_SUCCESS: "UPDATE_STATUS_CAPTION_SUCCESS",
  GET_INFO_USER_SUCCESS: "GET_INFO_USER_SUCCESS",
  UPDATE_NICK_NAME_SUCCESS: "UPDATE_NICK_NAME_SUCCESS",
  CHANGE_PASSWORD_SUCCESS: "CHANGE_PASSWORD_SUCCESS",

  PASSWORD_INVALID: "PASSWORD_INVALID",
  USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
  USERNAME_OR_PASSWORD_INVALID: "USERNAME_OR_PASSWORD_INVALID",
  USERNAME_IS_NOT_EXISTS: "USERNAME_IS_NOT_EXISTS",
  PASSWORD_IS_WRONG: "PASSWORD_IS_WRONG",
  EMAIL_INVALID: "EMAIL_INVALID",
  STATUS_CAPTION_INVALID: "STATUS_CAPTION_INVALID",
  NICK_NAME_INVALID: "NICK_NAME_INVALID",
};
